import { addDays, format } from "date-fns";
import type { Goal, Habit, Project, Task } from "./types";
import { uid } from "./utils";

function iso(d: Date) {
  return format(d, "yyyy-MM-dd");
}

export function buildSeed(now = new Date()) {
  const today = iso(now);
  const tomorrow = iso(addDays(now, 1));
  const inTwo = iso(addDays(now, 2));
  const inFive = iso(addDays(now, 5));
  const inTen = iso(addDays(now, 10));
  const inEighteen = iso(addDays(now, 18));
  const stamp = now.toISOString();

  const projectId = uid();
  const goalSaveId = uid();
  const goalCertId = uid();
  const habitWalk = uid();
  const habitRead = uid();
  const habitWater = uid();

  const projects: Project[] = [
    {
      id: projectId,
      name: "Website Project",
      description: "Client site refresh — reviews, quotes, and launch checklist.",
      createdAt: stamp,
    },
  ];

  const tasks: Task[] = [
    {
      id: uid(),
      title: "Morning Exercise",
      description: "30-minute walk or bodyweight session.",
      notes: "",
      kind: "todo",
      category: "personal",
      subcategory: "Health & Fitness",
      projectId: null,
      goalId: null,
      date: today,
      time: "06:30",
      priority: "medium",
      status: "completed",
      reminderOffsets: [10],
      repeat: { type: "daily" },
      subtasks: [],
      isHabit: true,
      isDemo: true,
      amount: null,
      createdAt: stamp,
      updatedAt: stamp,
      completedAt: stamp,
      completions: [today],
    },
    {
      id: uid(),
      title: "Call parents",
      description: "Weekend check-in.",
      notes: "",
      kind: "todo",
      category: "personal",
      subcategory: "Family",
      projectId: null,
      goalId: null,
      date: today,
      time: "19:30",
      priority: "high",
      status: "pending",
      reminderOffsets: [15],
      repeat: { type: "none" },
      subtasks: [],
      isHabit: false,
      isDemo: false,
      amount: null,
      createdAt: stamp,
      updatedAt: stamp,
      completedAt: null,
      completions: [],
    },
    {
      id: uid(),
      title: "Grocery shopping",
      description: "Milk, greens, fruit, coffee.",
      notes: "Prefer the evening market.",
      kind: "todo",
      category: "personal",
      subcategory: "Shopping",
      projectId: null,
      goalId: null,
      date: today,
      time: "18:30",
      priority: "medium",
      status: "pending",
      reminderOffsets: [30],
      repeat: { type: "weekly", days: [now.getDay()] },
      subtasks: [
        { id: uid(), title: "Vegetables", completed: false },
        { id: uid(), title: "Household", completed: false },
      ],
      isHabit: false,
      isDemo: false,
      amount: null,
      createdAt: stamp,
      updatedAt: stamp,
      completedAt: null,
      completions: [],
    },
    {
      id: uid(),
      title: "Read 20 pages",
      description: "Evening reading block.",
      notes: "",
      kind: "todo",
      category: "personal",
      subcategory: "Education",
      projectId: null,
      goalId: null,
      date: today,
      time: "21:00",
      priority: "low",
      status: "pending",
      reminderOffsets: [0],
      repeat: { type: "daily" },
      subtasks: [],
      isHabit: true,
      isDemo: false,
      amount: null,
      createdAt: stamp,
      updatedAt: stamp,
      completedAt: null,
      completions: [],
    },
    {
      id: uid(),
      title: "Project Review",
      description: "Walk through open tickets with the team.",
      notes: "",
      kind: "schedule",
      category: "professional",
      subcategory: "Reviews",
      projectId,
      goalId: null,
      date: today,
      time: "15:00",
      priority: "high",
      status: "pending",
      reminderOffsets: [15],
      repeat: { type: "none" },
      subtasks: [
        { id: uid(), title: "Collect status notes", completed: true },
        { id: uid(), title: "Prepare agenda", completed: false },
      ],
      isHabit: false,
      isDemo: true,
      amount: null,
      createdAt: stamp,
      updatedAt: stamp,
      completedAt: null,
      completions: [],
    },
    {
      id: uid(),
      title: "Client meeting",
      description: "Scope check for the homepage.",
      notes: "Bring the latest mock.",
      kind: "schedule",
      category: "professional",
      subcategory: "Meetings",
      projectId,
      goalId: null,
      date: today,
      time: "10:00",
      priority: "critical",
      status: "pending",
      reminderOffsets: [15, 60],
      repeat: { type: "none" },
      subtasks: [],
      isHabit: false,
      isDemo: false,
      amount: null,
      createdAt: stamp,
      updatedAt: stamp,
      completedAt: null,
      completions: [],
    },
    {
      id: uid(),
      title: "Send quotation",
      description: "Pricing for phase two.",
      notes: "",
      kind: "todo",
      category: "professional",
      subcategory: "Client Tasks",
      projectId,
      goalId: null,
      date: today,
      time: "12:30",
      priority: "high",
      status: "pending",
      reminderOffsets: [30],
      repeat: { type: "none" },
      subtasks: [],
      isHabit: false,
      isDemo: false,
      amount: null,
      createdAt: stamp,
      updatedAt: stamp,
      completedAt: null,
      completions: [],
    },
    {
      id: uid(),
      title: "Follow-up with customer",
      description: "Confirm last week's deliverable.",
      notes: "",
      kind: "reminder",
      category: "professional",
      subcategory: "Follow-ups",
      projectId,
      goalId: null,
      date: today,
      time: "17:30",
      priority: "medium",
      status: "pending",
      reminderOffsets: [10],
      repeat: { type: "none" },
      subtasks: [],
      isHabit: false,
      isDemo: false,
      amount: null,
      createdAt: stamp,
      updatedAt: stamp,
      completedAt: null,
      completions: [],
    },
    {
      id: uid(),
      title: "Finish project report",
      description: "Draft the weekly status for stakeholders.",
      notes: "",
      kind: "todo",
      category: "professional",
      subcategory: "Reports",
      projectId,
      goalId: goalCertId,
      date: tomorrow,
      time: "11:00",
      priority: "high",
      status: "pending",
      reminderOffsets: [60],
      repeat: { type: "none" },
      subtasks: [
        { id: uid(), title: "Outline", completed: true },
        { id: uid(), title: "Metrics", completed: false },
        { id: uid(), title: "Risks", completed: false },
      ],
      isHabit: false,
      isDemo: false,
      amount: null,
      createdAt: stamp,
      updatedAt: stamp,
      completedAt: null,
      completions: [],
    },
    {
      id: uid(),
      title: "Electricity Bill",
      description: "Monthly household electricity.",
      notes: "",
      kind: "payment",
      category: "financial",
      subcategory: "Utilities",
      projectId: null,
      goalId: null,
      date: today,
      time: "14:00",
      priority: "high",
      status: "pending",
      reminderOffsets: [1440, 60],
      repeat: { type: "monthly", day: now.getDate() },
      subtasks: [],
      isHabit: false,
      isDemo: true,
      amount: 2499,
      createdAt: stamp,
      updatedAt: stamp,
      completedAt: null,
      completions: [],
    },
    {
      id: uid(),
      title: "Home Loan EMI",
      description: "Scheduled auto-debit reminder.",
      notes: "Do not store account credentials here.",
      kind: "payment",
      category: "financial",
      subcategory: "EMI",
      projectId: null,
      goalId: null,
      date: inFive,
      time: "09:00",
      priority: "critical",
      status: "pending",
      reminderOffsets: [1440],
      repeat: { type: "monthly", day: Number(inFive.slice(8, 10)) },
      subtasks: [],
      isHabit: false,
      isDemo: false,
      amount: 15000,
      createdAt: stamp,
      updatedAt: stamp,
      completedAt: null,
      completions: [],
    },
    {
      id: uid(),
      title: "SIP",
      description: "Monthly investment reminder.",
      notes: "",
      kind: "payment",
      category: "financial",
      subcategory: "SIP",
      projectId: null,
      goalId: goalSaveId,
      date: inTen,
      time: "09:30",
      priority: "medium",
      status: "pending",
      reminderOffsets: [1440],
      repeat: { type: "monthly", day: Number(inTen.slice(8, 10)) },
      subtasks: [],
      isHabit: false,
      isDemo: false,
      amount: 5000,
      createdAt: stamp,
      updatedAt: stamp,
      completedAt: null,
      completions: [],
    },
    {
      id: uid(),
      title: "Health insurance",
      description: "Annual premium reminder.",
      notes: "",
      kind: "payment",
      category: "financial",
      subcategory: "Insurance",
      projectId: null,
      goalId: null,
      date: inEighteen,
      time: "10:00",
      priority: "high",
      status: "pending",
      reminderOffsets: [1440, 10080],
      repeat: { type: "yearly" },
      subtasks: [],
      isHabit: false,
      isDemo: false,
      amount: 2499,
      createdAt: stamp,
      updatedAt: stamp,
      completedAt: null,
      completions: [],
    },
    {
      id: uid(),
      title: "Buy birthday gift",
      description: "For next week's celebration.",
      notes: "",
      kind: "todo",
      category: "personal",
      subcategory: "Birthdays",
      projectId: null,
      goalId: null,
      date: inTwo,
      time: "16:00",
      priority: "medium",
      status: "pending",
      reminderOffsets: [60],
      repeat: { type: "none" },
      subtasks: [],
      isHabit: false,
      isDemo: false,
      amount: null,
      createdAt: stamp,
      updatedAt: stamp,
      completedAt: null,
      completions: [],
    },
  ];

  const goals: Goal[] = [
    {
      id: goalSaveId,
      title: "Save ₹1,00,000",
      description: "Emergency fund top-up this year.",
      category: "financial",
      targetDate: iso(addDays(now, 120)),
      targetValue: 100000,
      currentValue: 42000,
      unit: "₹",
      taskIds: tasks.filter((t) => t.goalId === goalSaveId).map((t) => t.id),
      milestones: [
        { id: uid(), title: "₹25,000", done: true },
        { id: uid(), title: "₹50,000", done: false },
        { id: uid(), title: "₹75,000", done: false },
        { id: uid(), title: "₹1,00,000", done: false },
      ],
      createdAt: stamp,
    },
    {
      id: goalCertId,
      title: "Complete certification",
      description: "Finish the professional course and exam.",
      category: "professional",
      targetDate: iso(addDays(now, 60)),
      targetValue: 12,
      currentValue: 7,
      unit: "modules",
      taskIds: [],
      milestones: [
        { id: uid(), title: "Core modules", done: true },
        { id: uid(), title: "Practice exam", done: false },
        { id: uid(), title: "Final exam", done: false },
      ],
      createdAt: stamp,
    },
    {
      id: uid(),
      title: "Exercise 100 days",
      description: "Show up, even if the session is short.",
      category: "personal",
      targetDate: iso(addDays(now, 90)),
      targetValue: 100,
      currentValue: 18,
      unit: "days",
      taskIds: [],
      milestones: [
        { id: uid(), title: "7-day streak", done: true },
        { id: uid(), title: "30 days", done: false },
        { id: uid(), title: "100 days", done: false },
      ],
      createdAt: stamp,
    },
  ];

  const yesterday = iso(addDays(now, -1));
  const twoBack = iso(addDays(now, -2));

  const habits: Habit[] = [
    {
      id: habitWalk,
      title: "Morning walk",
      category: "personal",
      days: [1, 2, 3, 4, 5, 6, 0],
      completions: { [twoBack]: true, [yesterday]: true, [today]: true },
      createdAt: stamp,
      isDemo: false,
    },
    {
      id: habitRead,
      title: "Reading",
      category: "personal",
      days: [1, 2, 3, 4, 5, 6, 0],
      completions: { [twoBack]: true, [yesterday]: true },
      createdAt: stamp,
      isDemo: false,
    },
    {
      id: habitWater,
      title: "Drink water",
      category: "personal",
      days: [1, 2, 3, 4, 5, 6, 0],
      completions: { [yesterday]: true },
      createdAt: stamp,
      isDemo: false,
    },
  ];

  return { projects, tasks, goals, habits };
}
